# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='picture',
            field=models.TextField(),
        ),
    ]
